spring:
  datasource:
    url: jdbc:mysql://mysql:3306/jpa_practice?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul
    username: root
    password: 19980223
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}
    region:
      static: ap-northeast-2
    s3:
      bucket: piney-community-bucket

lambda:
  file:
    endpoint: https://mfwizl6jg9.execute-api.ap-northeast-2.amazonaws.com/prod

jwt:
  secret-key: "7YyM7J2064uI44WL7YyM7J207YyFISHtlaDsiJjsnojslrQhIey9lOuqveydtOuaseydtOu0ieu0ieydtOynsQ=="
  token-expiration-seconds: 3600 # 1시간

cors:
  front: http://localhost:3000

logging:
  level:
    org.hibernate.SQL: debug

